[package]
name = "atcoder-rust"
version = "0.1.0"
authors = ["tjnt <3m2dyzxu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
